dist: xenial
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - "node_modules"
services:
  - postgresql
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - if [ ! -d ${HOME}/google-cloud-sdk ]; then
            curl https://sdk.cloud.google.com | bash;
        fi
    - gcloud auth activate-service-account --key-file service-account.json

install:
  - gcloud config set project viewing-party-gcp
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - bin/yarn
before_script:
  # - bin/rails db:prepare
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
script:
  # - bin/rails test
  - bundle exec rspec

cache:
  bundler: true
  yarn: true
  directories:
      - "node_modules"
      - "$HOME/google-cloud-sdk/"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_8ad82cc635a3_key -iv $encrypted_8ad82cc635a3_iv -in config/master.key.enc -out config/master.key -d
  - RAILS_ENV=production bin/rails assets:precompile

deploy:
  provider: script
  script: ./bin/deploy
  skip_cleanup: true
  on:
    branch: main

# language: ruby
# rbenv:
# - 2.5.3
# before_install:
# - nvm install 10
# addons:
#   postgresql: 9.6
# script:
# - bundle exec rails db:{create,migrate} RAILS_ENV=test
# - bundle exec rspec
# deploy:
#   provider: heroku
#   api_key:
#     secure: MOVIE_DB_API_KEY
#   app:
#   run: rails db:migrate
