dist: xenial
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - "node_modules"
services:
  - postgresql
before_install:
    - if [ ! -d ${HOME}/google-cloud-sdk ]; then
            curl https://sdk.cloud.google.com | bash;
        fi
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - bin/yarn
before_script:
  # - bin/rails db:prepare
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
script:
  # - bin/rails test
  - bundle exec rspec

cache:
  bundler: true
  yarn: true
  directories:
      - "node_modules"
      - "$HOME/google-cloud-sdk/"


# language: ruby
# rbenv:
# - 2.5.3
# before_install:
# - nvm install 10
# addons:
#   postgresql: 9.6
# script:
# - bundle exec rails db:{create,migrate} RAILS_ENV=test
# - bundle exec rspec
# deploy:
#   provider: heroku
#   api_key:
#     secure: MOVIE_DB_API_KEY
#   app:
#   run: rails db:migrate
